### PR TITLE
Snap build fixes

### PR DESCRIPTION
**Pull request by kenvandine**
Connect to lxd and build with flutter master

### CODE REVIEW

**Comment by jpnurmi** [comment]
Awesome, thanks! Does it also need "network" to access remote servers?
image

**Comment by kenvandine** [comment]
It didn't need it for me... I assumed lxd handles the downloading.  Did you connect the lxd plug?

Until we get the autoconnect declaration, you will need to connect it manually.

**Comment by jpnurmi** [comment]
LXD takes care of downloading images once given the server address and image fingerprint but the UI/client needs direct network access to browse remote images (simplestreams over HTTP). The list of "remotes" is a client-side thing:

```
$ lxc remote list
+-----------------+------------------------------------------+---------------+-------------+--------+--------+--------+
|      NAME       |                   URL                    |   PROTOCOL    |  AUTH TYPE  | PUBLIC | STATIC | GLOBAL |
+-----------------+------------------------------------------+---------------+-------------+--------+--------+--------+
| images          | https://images.linuxcontainers.org       | simplestreams | none        | YES    | NO     | NO     |
+-----------------+------------------------------------------+---------------+-------------+--------+--------+--------+
| local (current) | unix://                                  | lxd           | file access | NO     | YES    | NO     |
+-----------------+------------------------------------------+---------------+-------------+--------+--------+--------+
| ubuntu          | https://cloud-images.ubuntu.com/releases | simplestreams | none        | YES    | YES    | NO     |
+-----------------+------------------------------------------+---------------+-------------+--------+--------+--------+
| ubuntu-daily    | https://cloud-images.ubuntu.com/daily    | simplestreams | none        | YES    | YES    | NO     |
+-----------------+------------------------------------------+---------------+-------------+--------+--------+--------+
```

**Review by jpnurmi — APPROVED** [review]
Thanks, LGTM :+1:

**Pull request merged**
